export const route = {
  bible: 'Bible',
  bibleGuest: 'BibleGuest',
  login: 'Login',
  register: 'Register',
  googleRegister: 'GoogleRegister',
  welcome: 'Welcome',
  forgotPassword: 'ForgotPassword',
  Highlights: 'Highlights',
  readHistory: 'ReadHistory',
  profile: 'Profile',
  dailyDevotional: 'DailyDevotional',
  dailyDevotions: 'DailyDevotions',
  dailyExegesis: 'DailyExegesis',
  dailyVerse: 'DailyVerse',
  home: 'Home',
  homeLogin: 'HomeLogin',
  favorites: 'Favorites',
  notLogined: 'NotLoggedIn',
  bibleFirstLaunch: 'BibleFirstLaunch',
  notes: 'Notes',
  editProfile: 'EditProfile',
  extendedProfile: 'ExtendedProfile',
  readingPlan: 'ReadingPlan',
  planDetail: 'PlanDetail',
  dailyReading: 'DailyReading',
  voiceSettings: 'VoiceSettings',
  guestEntry: 'GuestEntry',
  notificationSettings: 'NotificationSettings',
  planBible: 'PlanBibleScreen',
  readingSettings: 'ReadingSettings',
  adminDashboard: 'AdminDashboard',
  adminDashboardLogin: 'AdminDashboardLogin',
  adminUsers: 'AdminUsers',
  adminActivity: 'AdminActivity',
  adminDailyVerse: 'AdminDailyVerse',
  adminDailyDevotion: 'AdminDailyDevotion',
  adminDailyExegesis: 'AdminDailyExegesis',
  adminTrivia: 'AdminTrivia',
  adminStudyTools: 'AdminStudyTools',
  adminBookPrologues: 'AdminBookPrologues',
  adminReadingPlans: 'AdminReadingPlans',
  adminReadingPlanDetail: 'AdminReadingPlanDetail',
  journal: 'Journal',
  journalEntry: 'JournalEntry',
  journalDetail: 'JournalDetail',
  adminJournalPrompts: 'AdminJournalPrompts',
  adminJournalTemplates: 'AdminJournalTemplates',
  adminJournalModeration: 'AdminJournalModeration',
  fullVerseExplanation: 'FullVerseExplanation',
  verseResources: 'VerseResources',
  wordStudy: 'WordStudy',
  search: 'Search',
  lab: 'Lab',
  labFlow: 'LabFlow',

  // Legacy Ledger (Phase 5+)
  legacyLedger: 'LegacyLedger',
  ledgerDetail: 'LedgerDetail',
  ledgerEntry: 'LedgerEntry',

  // Bible Trivia
  trivia: 'Trivia',
  adminTriviaPerformance: 'AdminTriviaPerformance',
  adminTriviaUserDetail: 'AdminTriviaUserDetail',
  sower: 'Sower',
  adminSubscriptions: 'AdminSubscriptions',
};
